#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Holberton School" when queried
#++    at the root with a curl GET request.

apt-get -y update
apt-get install -y nginx

echo 'Holberton School for the win!' > /var/www/html/index.html

service nginx restart
